<!--=============================
=            GELPADS            =
==============================-->
<section class="section gelpads">
	<div class="section_inner">
		<div class="section_detail">
			<span class="section_note">
				<?= __('Welcome to Basic Theme') ?>
			</span>
			<h2 class="section_heading">
				<?= __('Lorem ipsum dolor sit amet, consectetur.'); ?>
			</h2>
			<p class="section_para">
				<?= __('Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe vel voluptatibus quae nulla, quas ipsa facere doloribus! Ducimus vel, reiciendis enim doloribus id, ex modi. Cumque quisquam voluptas harum excepturi.') ?>
			</p>
			<div class="list_item">
				<span class="list_heading">
					<?= __('Lorem ipsum dolor sit amet.') ?>
				</span>
				<ul>
					<li>
						<a href="#" class="transition">
							<i class="fas fa-angle-double-right"></i> <?= __('Lorem'); ?>
						</a>
					</li>
					<li>
						<a href="#" class="transition">
							<i class="fas fa-angle-double-right"></i> <?= __('Lorem'); ?>
						</a>
					</li>
					<li>
						<a href="#" class="transition">
							<i class="fas fa-angle-double-right"></i> <?= __('Lorem'); ?>
						</a>
					</li>
					<li>
						<a href="#" class="transition">
							<i class="fas fa-angle-double-right"></i> <?= __('Lorem'); ?>
						</a>
					</li>
					<li>
						<a href="#" class="transition">
							<i class="fas fa-angle-double-right"></i> <?= __('Lorem'); ?>
						</a>
					</li>
					<li>
						<a href="#" class="transition">
							<i class="fas fa-angle-double-right"></i> <?= __('Lorem'); ?>
						</a>
					</li>
					<li>
						<a href="#" class="transition">
							<i class="fas fa-angle-double-right"></i> <?= __('Lorem'); ?>
						</a>
					</li>
					<li>
						<a href="#" class="transition">
							<i class="fas fa-angle-double-right"></i> <?= __('Lorem'); ?>
						</a>
					</li>
				</ul>
			</div>
		</div>
		<div class="section_img">
			<img src="<?php echo $this->getViewFileUrl('images/welcome.jpg'); ?>" alt="welcome image">
		</div>
	</div>
</section>