<!--============================
=            setups            =
=============================-->
<section class="section setups">
	<div class="section_inner">
		<div class="section_title">
			<h2 class="section_heading">
				<?= __('Lorem ipsum dolor.'); ?>
			</h2>
			<p class="section_para">
				<?= __('Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iusto, tempore explicabo! Cum cupiditate, quibusdam mollitia.'); ?>
			</p>
		</div>
		<div class="section_content">
			<div class="content_box">
				<span class="icon_img">
					<img src="<?= $this->getViewFileUrl('images/icon.png'); ?>" alt="icon">
				</span>
				<div>
					<a href="#" class="title_links">
						<?= __('Lorem ipsum.'); ?>
					</a>
				</div>
				<p class="section_para">
					<?= __('Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eaque, porro, impedit quas quis nulla aspernatur. Amet ex incidunt ipsa nihil?') ?>
				</p>
			</div>
			<div class="content_box">
				<span class="icon_img">
					<img src="<?= $this->getViewFileUrl('images/icon.png'); ?>" alt="icon">
				</span>
				<div>
					<a href="#" class="title_links">
						<?= __('Lorem ipsum.'); ?>
					</a>
				</div>
				<p class="section_para">
					<?= __('Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eaque, porro, impedit quas quis nulla aspernatur. Amet ex incidunt ipsa nihil?') ?>
				</p>
			</div>
			<div class="content_box">
				<span class="icon_img">
					<img src="<?= $this->getViewFileUrl('images/icon.png'); ?>" alt="icon">
				</span>
				<div>
					<a href="#" class="title_links">
						<?= __('Lorem ipsum.'); ?>
					</a>
				</div>
				<p class="section_para">
					<?= __('Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eaque, porro, impedit quas quis nulla aspernatur. Amet ex incidunt ipsa nihil?') ?>
				</p>
			</div>
			<div class="content_box">
				<span class="icon_img">
					<img src="<?= $this->getViewFileUrl('images/icon.png'); ?>" alt="icon">
				</span>
				<div>
					<a href="#" class="title_links">
						<?= __('Lorem ipsum.'); ?>
					</a>
				</div>
				<p class="section_para">
					<?= __('Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eaque, porro, impedit quas quis nulla aspernatur. Amet ex incidunt ipsa nihil?') ?>
				</p>
			</div>
		</div>
	</div>
</section>