<script type="text/javascript">
    var $zoho=$zoho || {};$zoho.salesiq = $zoho.salesiq ||
        {widgetcode:"991df4761d23b3fc084141186690b6e3ef912a4f977e6eee68621a7e9cda3392428913a6071f2851d27a8a2b1df87523", values:{},ready:function(){}};
    var d=document;s=d.createElement("script");s.type="text/javascript";s.id="zsiqscript";s.defer=true;
    s.src="https://salesiq.zoho.in/widget";t=d.getElementsByTagName("script")[0];t.parentNode.insertBefore(s,t);d.write("<div id='zsiqwidget'></div>");
</script>
<!--=====================================
=            WELCOME SECTION            =
======================================-->
<section class="section welcome">
	<div class="section_inner">
		<div class="section_img">
			<img src="<?php echo $this->getViewFileUrl('images/welcome.jpg'); ?>" alt="welcome image">
		</div>
		<div class="section_detail">
			<span class="section_note">
				<?= __('Welcome to Basic Theme') ?>
			</span>
			<h2 class="section_heading">
				<?= __('Lorem ipsum dolor sit amet, consectetur.'); ?>
			</h2>
			<p class="section_para">
				<?= __('Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe vel voluptatibus quae nulla, quas ipsa facere doloribus! Ducimus vel, reiciendis enim doloribus id, ex modi. Cumque quisquam voluptas harum excepturi.') ?>
			</p>
			<a href="#" class="read_more transition">
				<?= __('Read More') ?> <i class="fas fa-long-arrow-alt-right"></i>
			</a>
		</div>
	</div>
</section>
