<!--=====================================
=            WELCOME SECTION            =
======================================-->
<section class="section welcome">
	<div class="section_inner">
		<div class="section_img">
			<img src="<?php echo $this->getViewFileUrl('images/welcome.jpg'); ?>" alt="welcome image">
		</div>
		<div class="section_detail">
			<span class="section_note">
				<?= __('Welcome to Basic Theme') ?>
			</span>
			<h2 class="section_heading">
				<?= __('Lorem ipsum dolor sit amet, consectetur.'); ?>
			</h2>
			<p class="section_para">
				<?= __('Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe vel voluptatibus quae nulla, quas ipsa facere doloribus! Ducimus vel, reiciendis enim doloribus id, ex modi. Cumque quisquam voluptas harum excepturi.') ?>
			</p>
			<a href="#" class="read_more transition">
				<?= __('Read More') ?> <i class="fas fa-long-arrow-alt-right"></i>
			</a>
		</div>
	</div>
</section>