<section class="section quote">
	<div class="section_inner">
		<blockquote>
			<p>
				<?= __('Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptate sint ab repudiandae rerum atque aspernatur et nihil ea at molestiae labore error, inventore, sunt provident repellendus alias magni temporibus illum.'); ?>
			</p>
			<span>
				<?= __('-Aryan'); ?>
			</span>
		</blockquote>
	</div>
</section>