<section class="section banner">
	<div class="section_inner">
		<div class="owl-carousel owl-theme basic_slider">
			<div class="item">
				<img src="<?php echo $this->getViewFileUrl('Aryan_Banner/images/banner1.jpg'); ?>" alt="Banner">
			</div>
			<div class="item">
				<img src="<?php echo $this->getViewFileUrl('Aryan_Banner/images/banner2.jpg'); ?>" alt="Banner">
			</div>
			<div class="item">
				<img src="<?php echo $this->getViewFileUrl('Aryan_Banner/images/banner3.jpg'); ?>" alt="Banner">
			</div>
		</div>
	</div>
</section>
<script type="text/javascript">
    require(["jquery"], function($)
    {
        $('.basic_slider').owlCarousel({
            loop:true,
            margin:10,
            nav:true,
            dots:false,
            responsive:{
                0:{
                    items:1
                },
                600:{
                    items:1
                },
                1000:{
                    items:1
                }
            }
        });
    });
</script>
