<!--============================
=            FOOTER            =
=============================-->
<div class="footer_wrapper">
	<div class="footer_inner">	
		<p class="footer_description">
			<?= __('Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolorem, eum.'); ?>
		</p>
		<p class="footer_social">
			<a href="#" class="footer links facebook">
				<i class="fab fa-facebook-f"></i>
			</a>
			<a href="#" class="footer links twitter">
				<i class="fab fa-twitter"></i>
			</a>
			<a href="#" class="footer links linkedin">
				<i class="fab fa-linkedin-in"></i>
			</a>
			<a href="#" class="footer links gplus">
				<i class="fab fa-google-plus-g"></i>
			</a>
			<a href="#" class="footer links insta">
				<i class="fab fa-instagram"></i>
			</a>
		</p>
	</div>
	<div class="footer_inner">
		<h3 class="footer_heading">
			<?= __('Our Location'); ?>
		</h3>
		<p class="footer_address">
			<?= __('Lorem ipsum dolor sit amet.'); ?><br>
			<?= __('Lorem ipsum.'); ?><br>
			<?= __('226010'); ?>
		</p>
		<p class="footer_mail">
			<span>
				<?= __('Email:'); ?>
			</span>
			<a href="mailto:mail@yourdomin.com">
				<?= __('mail@yourdomain.com'); ?>
			</a>
		</p>
	</div>
	<div class="footer_inner">
		<h3 class="footer_heading">
			<?= __('Services'); ?>
		</h3>
		<ul>
			<li>
				<a href="#" class="links">
					<?= __('your links'); ?>
				</a>
			</li>
			<li>
				<a href="#" class="links">
					<?= __('your links'); ?>
				</a>
			</li>
			<li>
				<a href="#" class="links">
					<?= __('your links'); ?>
				</a>
			</li>
			<li>
				<a href="#" class="links">
					<?= __('your links'); ?>
				</a>
			</li>
		</ul>
	</div>
</div>
